"""
Persian UI labels for transcript PDF/DOCX exports.

Single source of truth — both exporters must use these constants so headings
and table labels never diverge.
"""

from __future__ import annotations

# Brand / cover
BRAND_NAME = "تورینگ"
REPORT_TITLE = "گزارش پیاده‌سازی متن"
MEETING_FALLBACK = "جلسه"
LOGO_PLACEHOLDER = "لوگو"
DEFAULT_PROJECT = "مرکز گفتار"

# Section headings
SECTION_MEETING_INFO = "اطلاعات جلسه"
SECTION_EXECUTIVE_SUMMARY = "خلاصه اجرایی"
SECTION_KEY_TOPICS = "موضوعات کلیدی"
SECTION_ACTION_ITEMS = "اقدامات"
SECTION_DECISIONS = "تصمیم‌ها"
SECTION_KEYWORDS = "کلیدواژه‌ها"
SECTION_TRANSCRIPT = "متن پیاده‌سازی شده"

# Table / metadata labels
LABEL_ORGANIZATION = "سازمان"
LABEL_MEETING_TITLE = "عنوان جلسه"
LABEL_PERSIAN_DATE = "تاریخ شمسی"
LABEL_GREGORIAN_DATE = "تاریخ میلادی"
LABEL_LANGUAGE = "زبان"
LABEL_DURATION = "مدت زمان"
LABEL_SPEAKERS = "گویندگان"
LABEL_WORDS = "تعداد کلمات"
LABEL_PROVIDER = "ارائه‌دهنده"
LABEL_FILE = "فایل"
LABEL_TIMELINE = "خط زمانی"

# Empty / placeholder copy
EMPTY_SUMMARY = "خلاصه‌ای موجود نیست."
EMPTY_TOPICS = "موضوعی موجود نیست."
EMPTY_ACTION_ITEMS = "اقدامی موجود نیست."
EMPTY_DECISIONS = "تصمیمی ثبت نشده است."
EMPTY_KEYWORDS = "کلیدواژه‌ای موجود نیست."
EMPTY_TRANSCRIPT = "متن پیاده‌سازی‌شده‌ای موجود نیست."

# Footer
FOOTER_GENERATED_BY = "تولیدشده توسط تورینگ"

# English UI labels that must never appear in rendered export bodies.
# Used by tests to catch regressions. Technical identifiers (e.g. language
# codes, provider codes, speaker names, transcript text) are excluded.
FORBIDDEN_ENGLISH_UI_LABELS: tuple[str, ...] = (
    "Transcript Report",
    "Meeting Information",
    "Executive Summary",
    "Key Topics",
    "Action Items",
    "Meeting title",
    "Persian date",
    "Gregorian date",
    "Generated by Turing",
    "No summary available.",
    "No topics available.",
    "No action items available.",
    "No decisions recorded.",
    "No keywords available.",
    "No transcript available.",
)

# Single-word English UI labels safe to assert in DOCX XML (not PDF metadata).
FORBIDDEN_ENGLISH_UI_WORDS: tuple[str, ...] = (
    "Organization",
    "Language",
    "Duration",
    "Speakers",
    "Words",
    "Provider",
    "Decisions",
    "Keywords",
)
