# Generated by Django 5.2.16 on 2026-07-26 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_enforcer",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "default_provider_code",
                    models.CharField(
                        default="speechmatics",
                        help_text="Provider code used when a job does not specify one.",
                        max_length=64,
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("local", "Local filesystem"),
                            ("s3", "AWS S3"),
                            ("azure", "Azure Blob Storage"),
                            ("gcs", "Google Cloud Storage"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "max_upload_bytes",
                    models.BigIntegerField(
                        default=524288000, help_text="Maximum upload size in bytes."
                    ),
                ),
                ("default_max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("poll_interval_seconds", models.FloatField(default=3.0)),
                ("poll_timeout_seconds", models.PositiveIntegerField(default=1800)),
                (
                    "auto_enqueue",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically enqueue Celery when a job is created.",
                    ),
                ),
                ("enable_diarization_default", models.BooleanField(default=True)),
                (
                    "default_language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty means provider auto-detect / provider default.",
                        max_length=16,
                    ),
                ),
                (
                    "api_require_auth",
                    models.BooleanField(
                        default=True,
                        help_text="Require authentication for Turing REST API.",
                    ),
                ),
                ("api_page_size", models.PositiveSmallIntegerField(default=25)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Platform configuration",
                "verbose_name_plural": "Platform configuration",
            },
        ),
        migrations.CreateModel(
            name="SpeechProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower values are preferred when selecting a default.",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leave blank to fall back to environment / Django settings.",
                        max_length=512,
                    ),
                ),
                ("base_url", models.URLField(blank=True, default="", max_length=512)),
                (
                    "default_language",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "operating_point",
                    models.CharField(
                        blank=True,
                        default="enhanced",
                        help_text="Speechmatics operating point (standard|enhanced).",
                        max_length=32,
                    ),
                ),
                ("enable_diarization", models.BooleanField(default=True)),
                (
                    "extra_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific options merged into job requests.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speech provider config",
                "verbose_name_plural": "Speech provider configs",
                "ordering": ["priority", "code"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("url", "External URL"),
                            ("stream", "Stream"),
                        ],
                        db_index=True,
                        default="upload",
                        max_length=16,
                    ),
                ),
                (
                    "use_case",
                    models.CharField(
                        db_index=True,
                        default="generic",
                        help_text="Product scenario label (meeting, crm_call, interview, voice_file).",
                        max_length=32,
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("local", "Local filesystem"),
                            ("s3", "AWS S3"),
                            ("azure", "Azure Blob Storage"),
                            ("gcs", "Google Cloud Storage"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="turing/media/%Y/%m/"
                    ),
                ),
                (
                    "object_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("byte_size", models.BigIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                (
                    "tenant_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Optional logical tenant / host-project isolation key.",
                        max_length=64,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turing_media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media asset",
                "verbose_name_plural": "Media assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[("stt", "Speech-to-Text")],
                        db_index=True,
                        default="stt",
                        max_length=32,
                    ),
                ),
                ("provider_code", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial", "Partial"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(db_index=True, default=100),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty triggers provider language detection when supported.",
                        max_length=16,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Diarization, punctuation, operating point, etc.",
                    ),
                ),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="turing.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing job",
                "verbose_name_plural": "Processing jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("provider_code", models.CharField(max_length=64)),
                (
                    "external_job_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial", "Partial"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="turing.processingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing attempt",
                "verbose_name_plural": "Processing attempts",
                "ordering": ["attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="turing.processingattempt",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="turing.processingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing log",
                "verbose_name_plural": "Processing logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turing_reviews_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turing_review_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review assignment",
                "verbose_name_plural": "Review assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("request_changes", "Request changes"),
                            ("reject", "Reject"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="turing.reviewassignment",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turing_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review decision",
                "verbose_name_plural": "Review decisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("full_text", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Marks the current primary transcript for the media asset.",
                    ),
                ),
                ("confidence_avg", models.FloatField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turing_approved_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="turing.processingjob",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="turing.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript",
                "verbose_name_plural": "Transcripts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "external_speaker_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="turing.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speaker",
                "verbose_name_plural": "Speakers",
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="transcript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_assignments",
                to="turing.transcript",
            ),
        ),
        migrations.CreateModel(
            name="TranscriptRevision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("human", "Human"),
                            ("system", "System"),
                        ],
                        default="human",
                        max_length=16,
                    ),
                ),
                (
                    "change_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Full structured snapshot (speakers + segments + full_text).",
                    ),
                ),
                ("diff", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turing_transcript_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="turing.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript revision",
                "verbose_name_plural": "Transcript revisions",
                "ordering": ["-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("start_ms", models.PositiveIntegerField(default=0)),
                ("end_ms", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "words",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional word-level timings: [{text, start_ms, end_ms, confidence}].",
                    ),
                ),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segments",
                        to="turing.speaker",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="turing.transcript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript segment",
                "verbose_name_plural": "Transcript segments",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="TuringMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("reviewer", "Reviewer"),
                            ("editor", "Editor"),
                            ("user", "User"),
                            ("viewer", "Viewer"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turing_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turing membership",
                "verbose_name_plural": "Turing memberships",
            },
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="turing_medi_uploade_78f058_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant_key", "-created_at"],
                name="turing_medi_tenant__95396b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["use_case", "-created_at"],
                name="turing_medi_use_cas_297e97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["status", "priority", "created_at"],
                name="turing_proc_status_361211_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["media", "capability"], name="turing_proc_media_i_b3d8fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["tenant_key", "-created_at"],
                name="turing_proc_tenant__a73b51_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="turing_job_idempotency_key_uniq",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="processingattempt",
            unique_together={("job", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["job", "created_at"], name="turing_proc_job_id_4186f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["level", "created_at"], name="turing_proc_level_ba6f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["media", "status"], name="turing_tran_media_i_cc7d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["status", "-updated_at"], name="turing_tran_status_c4d718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["is_primary", "media"], name="turing_tran_is_prim_8637a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="speaker",
            unique_together={("transcript", "label")},
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["assignee", "status"], name="turing_revi_assigne_75a640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["transcript", "status"], name="turing_revi_transcr_968e10_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transcriptrevision",
            unique_together={("transcript", "revision_number")},
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["transcript", "start_ms"], name="turing_tran_transcr_c3a98c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["speaker"], name="turing_tran_speaker_e428d2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transcriptsegment",
            unique_together={("transcript", "sequence")},
        ),
    ]
