# Generated by Django 5.2.16 on 2026-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformconfiguration",
            name="auto_enqueue",
            field=models.BooleanField(
                default=True,
                help_text="Automatically schedule the async Celery pipeline (submit → poll → fetch/persist) when a job is created.",
            ),
        ),
        migrations.AlterField(
            model_name="platformconfiguration",
            name="default_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default STT language for new jobs (e.g. fa, en). Required for Admin bulk job creation when language is not set explicitly.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="language_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="STT language (e.g. fa, en). Empty uses Platform / provider default language; job creation fails if no default is configured.",
                max_length=16,
            ),
        ),
    ]
