# Generated by Django 5.2.16 on 2026-07-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0003_encrypt_provider_api_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="audio_codec",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Detected codec when available.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="audio_format",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Detected container/format (e.g. wav, mp3).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="channels",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Detected channel count, if available.", null=True
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="sample_rate_hz",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Detected audio sample rate in Hz, if available.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="allowed_audio_extensions",
            field=models.CharField(
                blank=True,
                default="mp3,wav,m4a,webm,ogg",
                help_text="Comma-separated audio extensions allowed for upload.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="allowed_audio_mime_types",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional comma-separated MIME allow-list. Leave blank to use built-in defaults for the configured extensions.",
            ),
        ),
    ]
