# Generated by Django 5.2.16 on 2026-07-26 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0004_media_storage_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="word_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cached word count from provider words or segment text.",
            ),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="full_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Denormalized searchable transcript body.",
            ),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-agnostic metadata bag (raw provider payload refs, etc.).",
            ),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                help_text="Review workflow: draft → in_review → approved.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="transcriptsegment",
            name="provider_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Opaque provider segment metadata (kept for reprocessing/debug).",
            ),
        ),
        migrations.AlterField(
            model_name="transcriptsegment",
            name="words",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional provider-agnostic word list: [{text, start_ms, end_ms, confidence}, ...]. Mirrored in TranscriptWord when present.",
            ),
        ),
        migrations.CreateModel(
            name="TranscriptWord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("text", models.CharField(max_length=512)),
                ("start_ms", models.PositiveIntegerField(default=0)),
                ("end_ms", models.PositiveIntegerField(default=0)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional extras (speaker_label, provider ids, …).",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_entries",
                        to="turing.transcriptsegment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript word",
                "verbose_name_plural": "Transcript words",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["segment", "start_ms"],
                        name="turing_tran_segment_89b059_idx",
                    ),
                    models.Index(fields=["text"], name="turing_tran_text_8a7ac6_idx"),
                ],
                "unique_together": {("segment", "sequence")},
            },
        ),
    ]
