# Generated by Django 5.2.16 on 2026-07-30 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0023_job_org_scoped_idempotency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Connector/provider code (e.g. zoom, teams, google_meet, alocom).",
                        max_length=64,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Provider meeting/session id (not a recording file id).",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional participant metadata list (no secrets).",
                    ),
                ),
                (
                    "host_external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider host/owner id when known.",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-indexed provider baggage (not used as the identity key).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-started_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Connector/provider code (usually matches meeting.provider).",
                        max_length=64,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Provider recording/file id.",
                        max_length=255,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("ingesting", "Ingesting"),
                            ("ingested", "Ingested"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="discovered",
                        max_length=16,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-indexed recording baggage (file type, size hints, etc.).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recording",
                "verbose_name_plural": "Recordings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "ordering": ["speaker_label"],
                "verbose_name": "Speaker",
                "verbose_name_plural": "Speakers",
            },
        ),
        migrations.RenameIndex(
            model_name="mediaasset",
            new_name="turing_medi_organiz_9bde19_idx",
            old_name="turing_medi_organiz_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="mediaprocessingartifact",
            new_name="turing_medi_media_i_2bfd13_idx",
            old_name="turing_artifact_media_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="mediaprocessingartifact",
            new_name="turing_medi_organiz_dfa19c_idx",
            old_name="turing_artifact_org_status_idx",
        ),
        migrations.RenameIndex(
            model_name="processingjob",
            new_name="turing_proc_organiz_6ee80d_idx",
            old_name="turing_proc_organiz_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="providerwebhookdelivery",
            new_name="turing_prov_provide_3eead0_idx",
            old_name="turing_webhook_provider_job_idx",
        ),
        migrations.RenameIndex(
            model_name="transcript",
            new_name="turing_tran_organiz_4bd5b5_idx",
            old_name="turing_tran_organiz_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="transcriptanalysis",
            new_name="turing_tran_transcr_12f145_idx",
            old_name="turing_analysis_transcript_type_idx",
        ),
        migrations.RenameIndex(
            model_name="transcriptanalysis",
            new_name="turing_tran_organiz_dab4ba_idx",
            old_name="turing_analysis_org_type_idx",
        ),
        migrations.RenameIndex(
            model_name="turingmembership",
            new_name="turing_turi_organiz_ef077b_idx",
            old_name="turing_turi_organiz_7a8c01_idx",
        ),
        migrations.RenameIndex(
            model_name="turingmembership",
            new_name="turing_turi_user_id_8d5819_idx",
            old_name="turing_turi_user_id_9f2c11_idx",
        ),
        migrations.AddField(
            model_name="meeting",
            name="connector_installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings",
                to="turing.connectorinstallation",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="organization",
            field=models.ForeignKey(
                help_text="Owning organization (data boundary). Required.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetings",
                to="turing.organization",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="media",
            field=models.OneToOneField(
                blank=True,
                help_text="Turing media created from this recording (after ingest).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_recording",
                to="turing.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="turing.meeting",
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="organization",
            field=models.ForeignKey(
                help_text="Owning organization (data boundary). Required.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recordings",
                to="turing.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organization", "provider", "external_id"],
                name="turing_meeting_org_prov_ext",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organization", "-started_at"],
                name="turing_meeting_org_started",
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                fields=("organization", "provider", "external_id"),
                name="turing_meeting_org_provider_ext_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["organization", "provider", "external_id"],
                name="turing_recording_org_prov_ext",
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["meeting", "-created_at"], name="turing_recording_meeting"
            ),
        ),
        migrations.AddConstraint(
            model_name="recording",
            constraint=models.UniqueConstraint(
                fields=("organization", "provider", "external_id"),
                name="turing_recording_org_provider_ext_uniq",
            ),
        ),
    ]
