# Generated by Django 5.2.16 on 2026-07-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0024_meeting_recording_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptExportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_global",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        editable=False,
                        help_text="True when organization is empty (platform defaults).",
                    ),
                ),
                (
                    "show_meeting_title",
                    models.BooleanField(
                        default=True,
                        help_text="Include the meeting / media title on the cover and meeting table.",
                        verbose_name="Show meeting title",
                    ),
                ),
                (
                    "show_persian_date",
                    models.BooleanField(
                        default=True,
                        help_text="Show the Asia/Tehran calendar date in Jalali form.",
                        verbose_name="Show Persian (Jalali) date",
                    ),
                ),
                (
                    "show_gregorian_date",
                    models.BooleanField(
                        default=True,
                        help_text="Show the Asia/Tehran Gregorian calendar date.",
                        verbose_name="Show Gregorian date",
                    ),
                ),
                (
                    "show_duration",
                    models.BooleanField(
                        default=True,
                        help_text="Include media duration in cover and meeting information.",
                        verbose_name="Show duration",
                    ),
                ),
                (
                    "show_speakers",
                    models.BooleanField(
                        default=True,
                        help_text="Include speaker count / speaker list metadata.",
                        verbose_name="Show speakers",
                    ),
                ),
                (
                    "show_full_transcript",
                    models.BooleanField(
                        default=True,
                        help_text="Include the transcript dialogue section.",
                        verbose_name="Show full transcript",
                    ),
                ),
                (
                    "show_timeline",
                    models.BooleanField(
                        default=True,
                        help_text="Show start timestamps next to each speaker turn.",
                        verbose_name="Show timeline timestamps",
                    ),
                ),
                (
                    "show_ai_summary",
                    models.BooleanField(
                        default=False,
                        help_text="Include the AI executive summary section.",
                        verbose_name="Show executive summary",
                    ),
                ),
                (
                    "show_key_topics",
                    models.BooleanField(
                        default=False,
                        help_text="Include the AI key topics section.",
                        verbose_name="Show key topics",
                    ),
                ),
                (
                    "show_action_items",
                    models.BooleanField(
                        default=False,
                        help_text="Include the AI action items section.",
                        verbose_name="Show action items",
                    ),
                ),
                (
                    "show_decisions",
                    models.BooleanField(
                        default=False,
                        help_text="Include the decisions / key points section.",
                        verbose_name="Show decisions",
                    ),
                ),
                (
                    "show_keywords",
                    models.BooleanField(
                        default=False,
                        help_text="Include keyword chips derived from topics.",
                        verbose_name="Show keywords",
                    ),
                ),
                (
                    "show_provider",
                    models.BooleanField(
                        default=False,
                        help_text="Include the STT provider code in meeting information.",
                        verbose_name="Show speech provider",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for platform-wide defaults. Set an organization to store a future org-level override.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_export_settings",
                        to="turing.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript export settings",
                "verbose_name_plural": "Transcript export settings",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_global", True)),
                        fields=("is_global",),
                        name="turing_export_settings_one_global",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("organization__isnull", False)),
                        fields=("organization",),
                        name="turing_export_settings_one_per_org",
                    ),
                ],
            },
        ),
    ]
