# Generated by Django 5.2.16 on 2026-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0025_transcript_export_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="auto_generate_ai_analysis",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, enqueue AI insights automatically after transcription. When disabled, users trigger generation from the transcript page.",
            ),
        ),
    ]
