# Generated by Django 5.2.17 on 2026-08-07 19:19

import django.db.models.deletion
import turing.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turing", "0026_organization_auto_generate_ai_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "api_key",
                    turing.security.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Provider API key (stored encrypted).",
                        max_length=1024,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Lower values are preferred."
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="turing.speechproviderconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider credential",
                "verbose_name_plural": "Provider credentials",
                "ordering": ["priority", "last_used_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="processingattempt",
            name="provider_credential",
            field=models.ForeignKey(
                blank=True,
                help_text="Credential used for this provider execution attempt.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="turing.providercredential",
            ),
        ),
        migrations.AddIndex(
            model_name="providercredential",
            index=models.Index(
                fields=["provider", "is_active"], name="turing_cred_prov_active"
            ),
        ),
        migrations.AddIndex(
            model_name="providercredential",
            index=models.Index(
                fields=["provider", "cooldown_until"], name="turing_cred_prov_cool"
            ),
        ),
        migrations.AddIndex(
            model_name="providercredential",
            index=models.Index(
                fields=["provider", "priority"], name="turing_cred_prov_prio"
            ),
        ),
    ]
